In [89]:
import numpy as np
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

ModuleNotFoundError: No module named 'jax'

In [84]:
def funcao_alvo(z):
    return 1 - np.sin(z)

z = np.array([i*0.2*np.pi for i in range(6)]).reshape(-1, 1)
y = np.array([funcao_alvo(i*0.2*np.pi) for i in range(6)]).reshape(-1, 1)

In [90]:
!pip install jax

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\Thiago\anaconda3\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "C:\Users\Thiago\anaconda3\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Thiago\anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Thiago\anaconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Thiago\anaconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buf


    if not criterion.candidates:
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\Thiago\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, i

In [46]:
class Model:
    def __init__(self, x):
        self.x = x
    def forward(self, z):
        return self.x * np.array([z**2, z, 1]).T
    def __call__(self, z):
        return self.forward(z)

In [73]:
x0 = np.array([1/2, -1, 1]).reshape(-1, 1)

In [48]:
model = Model(x0)

In [49]:
model(2)

array([ 2., -2.,  1.])

In [50]:
def square_error(y_pred, y_truth):
    return (y_truth - y_pred)**2

In [43]:
z = 2
square_error(model(z), ground_truth(z))

array([3.64541666, 4.37103725, 0.82682181])

In [53]:
z

array([[0.        ],
       [0.62831853],
       [1.25663706],
       [1.88495559],
       [2.51327412],
       [3.14159265]])

In [66]:
equations = np.concatenate([z**2, z, np.ones((z.shape[0], 1))], axis=1)

In [83]:
predictions = equations @ x0
predictions

array([[1.        ],
       [0.56907356],
       [0.53293129],
       [0.8915732 ],
       [1.64499929],
       [2.79320955]])

In [80]:
equations

array([[0.        , 0.        , 1.        ],
       [0.39478418, 0.62831853, 1.        ],
       [1.5791367 , 1.25663706, 1.        ],
       [3.55305758, 1.88495559, 1.        ],
       [6.31654682, 2.51327412, 1.        ],
       [9.8696044 , 3.14159265, 1.        ]])

In [82]:
x0

array([[ 0.5],
       [-1. ],
       [ 1. ]])

In [85]:
y

array([[1.        ],
       [0.41221475],
       [0.04894348],
       [0.04894348],
       [0.41221475],
       [1.        ]])

In [88]:
((y - predictions)**2).sum()

5.704231918128572